pdf_processing:
  max_pages: 50
  min_sentence_length: 10
  encoding: 'utf-8'

ml_models:
  spacy_model: 'en_core_web_sm'
  tfidf_max_features: 50
  tfidf_ngram_range: [1, 2]

question_generation:
  total_questions: 40
  difficulty_distribution:
    easy: 0.4
    medium: 0.4
    hard: 0.2
  question_types:
    - definition
    - concept
    - application
    - fill_blank

output:
  format: 'pdf'
  include_answers: true
  group_by_difficulty: true
  output_dir: 'data/output'
